/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  instructor: InstructorReference;
  category: CategoryReference;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level?: "Beginner" | "Intermediate" | "Advanced";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  duration?: string;
  freePreview?: boolean;
  studentCount?: number;
  keyPoints?: Array<string>;
  proTip?: string;
  notes?: PortableText;
  resources?: Array<
    {
      _key: string;
    } & LessonResource
  >;
};

export type PortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: PortableText;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type LessonResource = {
  _type: "lessonResource";
  resourceType: "pdf" | "link" | "code" | "download" | "article";
  title: string;
  description?: string;
  url: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?: string;
  title: string;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | InstructorReference
  | CategoryReference
  | SanityImageAssetReference
  | Course
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Lesson
  | PortableText
  | Instructor
  | Category
  | LessonReference
  | Module
  | LessonResource
  | LearningOutcome
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/queries/categories.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "courseCount": count(*[_type == "course" && references(^._id)])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  courseCount: number;
}>;

// Source: ../sanity/queries/categories.ts
// Variable: CATEGORY_SLUGS_QUERY
// Query: *[_type == "category" && defined(slug.current)]{ "slug": slug.current }
export type CATEGORY_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    description,    "courses": *[_type == "course" && references(^._id)] | order(popular desc, title asc) {      _id,      title,      "slug": slug.current,      summary,      level,      price,      popular,      coverImage {   "alt": coalesce(alt, ""),  asset->{    _id,    url,    metadata { lqip, dimensions }  } }    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string | null;
    level: "Advanced" | "Beginner" | "Intermediate" | null;
    price: number | null;
    popular: boolean | null;
    coverImage: {
      alt: string | "";
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  }>;
} | null;

// Source: ../sanity/queries/courses.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(popular desc, title asc) {      _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  coverImage {   "alt": coalesce(alt, ""),  asset->{    _id,    url,    metadata { lqip, dimensions }  } },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  photo {   "alt": coalesce(alt, ""),  asset->{    _id,    url,    metadata { lqip, dimensions }  } } },  "category": category->{   _id,  title,  "slug": slug.current },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "durationSeconds": math::sum(modules[].lessons[]->duration)  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    alt: string | "";
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      alt: string | "";
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  moduleCount: number | null;
  lessonCount: number | null;
  durationSeconds: null | number;
}>;

// Source: ../sanity/queries/courses.ts
// Variable: COURSES_COUNT_QUERY
// Query: count(*[_type == "course" && defined(slug.current)])
export type COURSES_COUNT_QUERY_RESULT = number;

// Source: ../sanity/queries/courses.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)]{ "slug": slug.current }
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../sanity/queries/courses.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  coverImage {   "alt": coalesce(alt, ""),  asset->{    _id,    url,    metadata { lqip, dimensions }  } },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  photo {   "alt": coalesce(alt, ""),  asset->{    _id,    url,    metadata { lqip, dimensions }  } } },  "category": category->{   _id,  title,  "slug": slug.current },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "durationSeconds": math::sum(modules[].lessons[]->duration),    "learningOutcomes": learningOutcomes[]{      _key,      icon,      title,      description    },    "modules": modules[]{   _key,  title,  summary,  "lessons": lessons[]->{   _id,  title,  "slug": slug.current,  duration,  freePreview,  studentCount,  keyPoints,  poster {   "alt": coalesce(alt, ""),  asset->{    _id,    url,    metadata { lqip, dimensions }  } } } }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    alt: string | "";
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      alt: string | "";
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  moduleCount: number | null;
  lessonCount: number | null;
  durationSeconds: null | number;
  learningOutcomes: Array<{
    _key: string;
    icon: string | null;
    title: string;
    description: string | null;
  }> | null;
  modules: Array<{
    _key: string;
    title: string;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      duration: string | null;
      freePreview: boolean | null;
      studentCount: number | null;
      keyPoints: Array<string> | null;
      poster: {
        alt: string | "";
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
      } | null;
    }> | null;
  }> | null;
} | null;

// Source: ../sanity/queries/instructors.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] | order(name asc) {    _id,    name,    "slug": slug.current,    expertise,    photo {   "alt": coalesce(alt, ""),  asset->{    _id,    url,    metadata { lqip, dimensions }  } }  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  expertise: Array<string> | null;
  photo: {
    alt: string | "";
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../sanity/queries/instructors.ts
// Variable: INSTRUCTOR_SLUGS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)]{ "slug": slug.current }
export type INSTRUCTOR_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../sanity/queries/instructors.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    expertise,    bio,    photo {   "alt": coalesce(alt, ""),  asset->{    _id,    url,    metadata { lqip, dimensions }  } },    "courses": *[_type == "course" && references(^._id)] | order(title asc) {      _id,      title,      "slug": slug.current,      summary,      level,      coverImage {   "alt": coalesce(alt, ""),  asset->{    _id,    url,    metadata { lqip, dimensions }  } }    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  expertise: Array<string> | null;
  bio: PortableText | null;
  photo: {
    alt: string | "";
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string | null;
    level: "Advanced" | "Beginner" | "Intermediate" | null;
    coverImage: {
      alt: string | "";
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  }>;
} | null;

// Source: ../sanity/queries/lessons.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)]{ "slug": slug.current }
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../sanity/queries/lessons.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    videoUrl,    duration,    freePreview,    studentCount,    keyPoints,    proTip,    notes,    poster {   "alt": coalesce(alt, ""),  asset->{    _id,    url,    metadata { lqip, dimensions }  } },    "resources": resources[]{      _key,      resourceType,      title,      description,      url    },    "course": *[_type == "course" && references(^._id)][0]{      _id,      title,      "slug": slug.current,      "instructor": instructor->{ _id, name, "slug": slug.current },      "modules": modules[]{        _key,        title,        "lessonIds": lessons[]._ref      }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  videoUrl: string;
  duration: string | null;
  freePreview: boolean | null;
  studentCount: number | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  notes: PortableText | null;
  poster: {
    alt: string | "";
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  resources: Array<{
    _key: string;
    resourceType: "article" | "code" | "download" | "link" | "pdf";
    title: string;
    description: string | null;
    url: string;
  }> | null;
  course: {
    _id: string;
    title: string;
    slug: string;
    instructor: {
      _id: string;
      name: string;
      slug: string;
    };
    modules: Array<{
      _key: string;
      title: string;
      lessonIds: Array<string> | null;
    }> | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "courseCount": count(*[_type == "course" && references(^._id)])\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)]{ "slug": slug.current }\n': CATEGORY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "courses": *[_type == "course" && references(^._id)] | order(popular desc, title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      level,\n      price,\n      popular,\n      coverImage { \n  "alt": coalesce(alt, ""),\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n }\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)] | order(popular desc, title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  coverImage { \n  "alt": coalesce(alt, ""),\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  "alt": coalesce(alt, ""),\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n }\n },\n  "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "durationSeconds": math::sum(modules[].lessons[]->duration)\n\n  }\n': COURSES_QUERY_RESULT;
    '\n  count(*[_type == "course" && defined(slug.current)])\n': COURSES_COUNT_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)]{ "slug": slug.current }\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  coverImage { \n  "alt": coalesce(alt, ""),\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  "alt": coalesce(alt, ""),\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n }\n },\n  "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "durationSeconds": math::sum(modules[].lessons[]->duration)\n,\n    "learningOutcomes": learningOutcomes[]{\n      _key,\n      icon,\n      title,\n      description\n    },\n    "modules": modules[]{ \n  _key,\n  title,\n  summary,\n  "lessons": lessons[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  duration,\n  freePreview,\n  studentCount,\n  keyPoints,\n  poster { \n  "alt": coalesce(alt, ""),\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n }\n }\n }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    expertise,\n    photo { \n  "alt": coalesce(alt, ""),\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n }\n  }\n': INSTRUCTORS_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)]{ "slug": slug.current }\n': INSTRUCTOR_SLUGS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    expertise,\n    bio,\n    photo { \n  "alt": coalesce(alt, ""),\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n },\n    "courses": *[_type == "course" && references(^._id)] | order(title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      level,\n      coverImage { \n  "alt": coalesce(alt, ""),\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n }\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)]{ "slug": slug.current }\n': LESSON_SLUGS_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    videoUrl,\n    duration,\n    freePreview,\n    studentCount,\n    keyPoints,\n    proTip,\n    notes,\n    poster { \n  "alt": coalesce(alt, ""),\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n },\n    "resources": resources[]{\n      _key,\n      resourceType,\n      title,\n      description,\n      url\n    },\n    "course": *[_type == "course" && references(^._id)][0]{\n      _id,\n      title,\n      "slug": slug.current,\n      "instructor": instructor->{ _id, name, "slug": slug.current },\n      "modules": modules[]{\n        _key,\n        title,\n        "lessonIds": lessons[]._ref\n      }\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
  }
}
